### ISSUE TITLE
Support For URL Grouping?

### ISSUE THREAD

**Issue by dvngnt** [k6io/postman-to-k6#114]
There are instances where identical requests or similar requests should be grouped, e.g., Logging in.
I'm not aware of a way to add this metadata to postman or a converted script, but It would be a great QoL feature for running k6 in the cloud. 

<img width="272" alt="image" src="https://user-images.githubusercontent.com/9191505/123317972-af21b100-d4fc-11eb-9a52-52ca7b27b545.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/9191505/123318213-f9a32d80-d4fc-11eb-8e20-913662c0a330.png">

**Comment by thim81** [comment]
In postman, you can define folders or tags. Is this a sufficient “grouping” manner? 


![](https://assets.postman.com/postman-docs/collections-v8.jpg)

**Comment by thim81** [comment]
@dvngnt If you use the folders in Postman, postman-to-k6 will generate the script in "groups" based on the folders.

<img width="518" alt="CleanShot 2021-06-28 at 14 38 07@2x" src="https://user-images.githubusercontent.com/952446/123637630-88c28500-d81e-11eb-8e24-cd833de3dc04.png">

**Comment by dvngnt** [comment]
Thanks for the solutions @thim81 ; I didn't know about the folder to group option. This will be useful when the requests are consecutive. 

The other instance I was thinking about is say I have requests A, B, C. Requests A and C should be grouped, but not B. Is it possible to surround A and C with the same group value for k6 to aggregate?

**Comment by thim81** [comment]
If you organise them like that in Postman, they will be grouped like that in K6.

the postman-to-k6 package converts your Postman collection into a K6 script.

If you use --seperate parameter (https://github.com/k6io/postman-to-k6#separate)

The package will create seperate scripts per postman request, in seperate files.
In the K6 script file you can find the references to each individual request and this will allow you play around with the order as you wish.

@simskij did a great job when creating this package since it is really powerful and flexible for converting your postman to K6.

**Comment by dvngnt** [comment]
@thim81 I'm currently working with the split output. I see that it's possible to surround requests with a group inside the default function. This is a workable solution Thank you!, but it might more modular for the data to live in the request itself. 

Do you know if it's possible to add that tag/group to the individual request.js file something like https://k6.io/docs/using-k6/http-requests/#url-grouping

**Comment by thim81** [comment]
Could you share what you want to do with it? So that I can beter understand the use-case?

Is the tagging for reporting purposes? Or for something else?

**Comment by dvngnt** [comment]
The application I'm testing has a few APIs that will call every 30 sec. It's the exact same request so I duplicate the request in postman and place it throughout the collection. When I covert the collection to a k6 script, it would be cool to have that duplicated request be a part of its own group.

One possible way might be surrounding the call with a group whenever the request is called, but it might be more efficient to add that group or tag to the request itself. so the actual k6 script is cleaner. 

The next step would include removing the duplicate requests.js and just call the first one, but that's a separate code cleaning issue.

**Comment by dvngnt** [comment]
@thim81 folders kinda work, but if you have the same request multiple folders they get grouped together, and maybe on one level they should, but it would be nice to have a tag that works across groups for metrics.

**Comment by thim81** [comment]
@dvngnt Since postman-to-k6 is based on the Postman collection data, what would you use within the Postman collection to base your tag.name on?

Lets take this example:
![CleanShot 2021-06-29 at 09 13 12](https://user-images.githubusercontent.com/952446/123753528-4058a500-d8ba-11eb-95a0-da6d66749432.png)
![CleanShot 2021-06-29 at 09 13 34](https://user-images.githubusercontent.com/952446/123753582-4f3f5780-d8ba-11eb-9616-3b03742c4fb5.png)


expected K6 tag:
```
http.get(`http://example.com/crm/leads?raw=true&cursor=&limit=20`, {
    tags: { name: '?????' },
  });
```

We have in Postman the following info available:
- Folder name (Leads)
- Request name (List Leads)
- Request path ({{baseUrl}}/crm/leads?raw=true&cursor=&limit=20)

There is no option to "tag" a request with metadata in Postman, so we have to find a useful convention.

Request name or request path seem very logical, 

```
http.get(`http://example.com/crm/leads?raw=true&cursor=&limit=20`, {
    tags: { name: 'List Leads' },
  });
```

**Comment by dvngnt** [comment]
@thim81 good point, postman doesn't have a great tagging solution for k6 to plug into.

I'm managing with the folder solution.

Thanks

**Comment by thim81** [comment]
@dvngnt I m looking to create a PR to have some sort or K6 tag generation in place in K6, for reporting grouping. 

Your use-case was more around request organisation? Or also for reporting?

**Comment by dvngnt** [comment]
@thim81 i would say more for reporting. Groups and folders seem to work well for organizations.

There are times where a request might be /user/userId where id is some unique integer and k6 complains about too many metrics and will suggest URL grouping. Which I don't believe folders will solve.

**Comment by thim81** [comment]
@dvngnt it matches with my reporting use-case. 

would you consider any of the following info available in Postman, as useful for a k6 reporting tag?

- Folder name (Leads)
- Request name (List Leads)
-?Request path ({{baseUrl}}/crm/leads?raw=true&cursor=&limit=20)

or something else?

**Comment by dvngnt** [comment]
I'm thinking the request name is the most useful. I think by default users will give a request a name before creating a folder.

**Comment by thim81** [comment]
@dvngnt 

In the meantime, I faced the same issue and some others (#125). After some thought, I found a way and created a PR and a forked NPM package version that contains the feature to set K6 request tags. Have a look at readme: https://www.npmjs.com/package/@apideck/postman-to-k6#k6-request-tag that explains how to use it.

Replace in your packages.json:
```
"dependencies": {
    "postman-to-k6": "^1.5.0"
  }
```
to
```
"dependencies": {
    "@apideck/postman-to-k6": "^1.8.0"
  }
```
